change file name

diff --git a/JenkinsFile.jdp b/JenkinsFile.jdp
--- a/JenkinsFile.jdp
+++ b/JenkinsFile.jdp
@@ -68,17 +68,17 @@ pipeline {
             }
         }
         stage('Example IF') {
-            if (env.BRANCH_NAME != 'master') {
-                echo 'I only execute on the master branch'
-            } else {
-                echo 'I execute elsewhere'
-                try {
-                    sh 'exit 1'
-                }
-                catch (exc) {
-                    echo 'Something failed, I should sound the klaxons!'
-                }
-            }
+            //.BRANCH_NAME != 'master') {
+            echo 'I only execute on the master branch'
+            //} else {
+            //    echo 'I execute elsewhere'
+            //    try {
+            //        sh 'exit 1'
+            //    }
+            //    catch (exc) {
+            //        echo 'Something failed, I should sound the klaxons!'
+            //    }
+            //}
         }
         stage('Do we Push') {
             //when {
